---
- name: Ping servers
  hosts: all
  vars:
    key1: True
    key2: "value2"
  gather_facts: false
  tasks:
    - name: Ping
      ping:

    - name: Print variables
      when: ansible_distribution is defined
      debug:
        msg: "OS = {{  ansible_distribution  }}"